### ISSUE TITLE
Can't install webtorrent-cli in npm

### ISSUE THREAD

**Issue by asimovc** [webtorrent/webtorrent-cli#313]
**What version of this package are you using?**
npm version

**What operating system, Node.js, and npm version?**
OS: Kiss Linux (musl and busybox based distro)
Node.js: v22.3.0
Npm: v10.8.1

**What happened?**
Can't install webtorrent-cli with `npm install webtorrent-cli -g

`**What did you expect to happen?**
Installation complete of webtorrent-cli

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by asimovc** [comment]
Here some [logs](https://0x0.st/XcIU.log)

**Comment by SilentBot1** [comment]
Hey @asimovc,

WebTorrent >= 2.3.0 now has WebRTC support, provided by the dependency `node-datachannel`.

`node-datachannel` [provides prebuilds](https://github.com/murat-dogan/node-datachannel?tab=readme-ov-file#supported-platforms) of `libdatachannel` (the underlying native library) for all officially supported versions of NodeJS, but the musl version of NodeJS is considered unofficial, and is not currently provided.

If you wish to use `webtorrent>=2.3.0` or `webtorrent-cli>=5.0.0` on musl, you must install the build requirements for `libdatachannel`, which can be done by running the following command: `apk add build-base cmake git openssl-libs-static openssl-dev`.

Alternatively, you can downgrade `webtorrent` to `<2.3.0` or `webtorrent-cli` to `<5.0.0`, though from my little testing, the `utp-native` dependency also appears to cause issues and is segfaulting currently.

We're investigating whether we can help `node-datachannel` provide a pre-built version of `libdatachannel` for musl so you do not need to install and build this locally and also fix any outstanding issues with `utp-native`, though as we don't officially support musl, this is not a priority from our side unfortunately.

**Comment by asimovc** [comment]
I have cmake 3.29.5-1, openssl 3.3.1-1 and git 2.45.2-1

**Comment by SilentBot1** [comment]
Hi @asimovc,

The error specifically in your build appears to be:
```
1623 error /home/hellboy/.npm/lib/node_modules/webtorrent-cli/node_modules/node-datachannel/build/_deps/libdatachannel-src/src/h264rtpdepacketizer.cpp: In member function 'virtual void rtc::H264RtpDepacketizer::incoming(rtc::message_vector&, const rtc::message_callback&)':
1623 error /home/hellboy/.npm/lib/node_modules/webtorrent-cli/node_modules/node-datachannel/build/_deps/libdatachannel-src/src/h264rtpdepacketizer.cpp:116:29: error: 'remove_if' is not a member of 'std'; did you mean 'remove_cv'?
1623 error   116 |         messages.erase(std::remove_if(messages.begin(), messages.end(),
1623 error       |                             ^~~~~~~~~
1623 error       |                             remove_cv
```

This appears to relate to the issue https://github.com/paullouisageneau/libdatachannel/issues/1173 on `libdatachannel`, but this was fixed in May in this PR: https://github.com/paullouisageneau/libdatachannel/pull/1183

From a fresh alpine container, I can successfully install `webtorrent-cli` as seen below, with the exact above dependencies: 
![image](https://github.com/webtorrent/webtorrent-cli/assets/15065825/5aa93e16-0154-498d-86ac-cd24ffbd2475)


Can you clear out anything you have cached, and try this again?

**Comment by asimovc** [comment]
I cleared my _ccache in node install dir and still not build

**Comment by SilentBot1** [comment]
I've made a PR [here](https://github.com/murat-dogan/node-datachannel/pull/264) which adds musl prebuilds for `libdatachannel` to `node-datachannel`, which should remove the requirement for you to need to build this locally once implemented.

**Comment by asimovc** [comment]
@SilentBot1 Thanks i also made a issue about the version, i seems `node-datachannel` is not in the latest [version](https://github.com/paullouisageneau/libdatachannel/issues/1213#issuecomment-2172752538) of `libdatachannel` that's why i get these failed build

**Comment by asimovc** [comment]
@SilentBot1 node-datachannel already made a PR that builds fine in musl, please update the dependencies version

**Comment by SilentBot1** [comment]
I'm aware @asimovc, It was my PR https://github.com/murat-dogan/node-datachannel/pull/264.

I will update the dependency once they fix OSX builds, which are currently not building.

**Comment by SilentBot1** [comment]
Just to provide an update, you should now be able to install this app on Alpine / musl-based systems, but utp-native will still throw a segfault due to not having musl builds as [this](https://github.com/mafintosh/utp-native/pull/51) pr has not been merged/reviewed.

**Comment by asimovc** [comment]
@SilentBot1 is not solved, reopen please
